### ISSUE TITLE
Deadlock releasing request pad for nvstreammux

### ISSUE THREAD

**Issue by rjhowell44** [canammex-tech/deepstream-services-library#206]
@Sscsmatrix 
The issue you mentioned earlier today... about the deadlock you see shutting down your script.

It has been reported to others... covered on the thread here
https://devtalk.nvidia.com/default/topic/1064179/deadlock-in-gst_element_release_request_pad-with-nvstreammux/

Looks like they're still waiting for an answer from NVIDIA

**Comment by rjhowell44** [comment]
@Sscsmatrix I found the secret sauce on another thread... and this has been fixed.  Your script should shut down without hanging.

**Comment by Sscsmatrix** [comment]
@rjhowell44 So I still have the problem.  I will try and obtain some debug logs
